# Generated by Django 3.1.2 on 2020-12-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabeleleiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=12)),
                ('data_criacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('duracao', models.PositiveIntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.DateTimeField()),
                ('horaFim', models.DateTimeField()),
                ('idCabeleleiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabeleleiros.cabeleleiro')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabeleleiros.cliente')),
                ('idServico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabeleleiros.servico')),
            ],
        ),
    ]
